# Generated by Django 2.1.4 on 2018-12-09 00:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiking', '0002_auto_20181209_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiking',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
