# Generated by Django 2.1.4 on 2018-12-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiking', '0003_auto_20181209_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiking',
            name='elevation',
            field=models.IntegerField(default=3000),
            preserve_default=False,
        ),
    ]
